### ISSUE TITLE
Test OGNI-DC on kitti-tracking

### ISSUE THREAD

**Issue by maggiesong7** [princeton-vl/OGNI-DC#3]
Many thanks for your work on depth completion. It's a good job but I met some problems when trying to test it on the Kitti-tracking dataset. I found that there were always some obvious artifacts on the top of the image, as shown below. Did I set something wrong? BTW, I see that the `spn_type` of provided ckpts is set to be `dyspn`. Can we solve these artifacts by changing it to `nlspn`?
![raw_depths](https://github.com/user-attachments/assets/2b5fb2eb-5924-4607-a4ea-f41c0936fe06)
Here are my parameters:
```
GRU_iters: 5  
backbone_mode: "rgbd"
gru_hidden_dim: 64
gru_context_dim: 64
prop_time: 6 
prop_kernel: 3
conf_prop: True
spn_type: "dyspn"
pred_depth: False
pred_confidence_input: 1
backbone_output_downsample_rate: 4
conf_min: 1.0
depth_downsample_method: "min"
depth_activation_format: "linear"
training_depth_mask_out_rate: 0.0
pred_context_feature: True
optim_layer_input_clamp: 100.0
integration_alpha: 5.0
```
Waiting for your reply. Thanks.

**Comment by maggiesong7** [comment]
Besides, the final prediction always has some negative values, while the ideal minimum depth value needs to be greater than 0.

**Comment by zuoym15** [comment]
Hi,

The artifacts are expected for the sky area, as the sky has neither sparse depth points nor ground-truth supervision during training. Negative values are also possible because we predict depth gradients instead of depth, and you can get negative values after integration. 
None of these would affect the validation performance, but if that really annoys you I would recommend masking out the sky with a separate segmentation model. 
You can also compare with the visualizations on the official KITTI benchmark to see if the depth map patterns you got roughly match: https://www.cvlibs.net/datasets/kitti/eval_depth_detail.php?benchmark=depth_completion&result=a7a0b00e2a82bc66b8e2f3703249b8d8b5818741
